### ISSUE TITLE
Specify minimum TeamCity server build

### ISSUE THREAD

**Issue by dtretyakov** [vyadh/teamcity-azure-keyvault-plugin#2]
Since this plugin is compatible with TeamCity 2018.1+ it would be great to reflect it in the plugin descriptor like that:
```
teamcity {
        server {
            descriptor {
                // ...
                minimumBuild = "58245"
            }
        }
}
```

It will help JetBrains plugins repository and TeamCity display warnings about incompatible versions.

**Comment by vyadh** [comment]
Good point. Thanks, I'll submit a fixed version...
